-- Migration: Setup pg_cron for Automated Jobs
-- Description: Enables pg_cron and creates scheduled jobs for cleanups and reports
-- Date: 2025-11-10

-- Enable pg_cron extension
CREATE EXTENSION IF NOT EXISTS pg_cron;

-- Grant usage on cron schema to postgres role
GRANT USAGE ON SCHEMA cron TO postgres;

-- Create enhanced cleanup function that handles all old data
CREATE OR REPLACE FUNCTION public.scheduled_cleanup_old_data()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  deleted_tokens int;
  deleted_events int;
  deleted_embeddings int;
BEGIN
  -- Delete expired/used tokens older than 7 days
  DELETE FROM public.password_reset_tokens
  WHERE (expires_at < now() - interval '7 days')
     OR (used = true AND created_at < now() - interval '7 days');
  GET DIAGNOSTICS deleted_tokens = ROW_COUNT;

  -- Delete security events older than 90 days (keep 3 months for audit)
  DELETE FROM public.security_events
  WHERE created_at < now() - interval '90 days';
  GET DIAGNOSTICS deleted_events = ROW_COUNT;

  -- Delete old message embeddings (older than 1 year)
  DELETE FROM public.message_embeddings
  WHERE created_at < now() - interval '1 year';
  GET DIAGNOSTICS deleted_embeddings = ROW_COUNT;

  -- Log cleanup results
  RAISE NOTICE 'Cleanup completed: % tokens, % events, % embeddings deleted',
    deleted_tokens, deleted_events, deleted_embeddings;
END;
$$;

COMMENT ON FUNCTION public.scheduled_cleanup_old_data IS 'Scheduled cleanup of old tokens, events, and embeddings';

-- Create function to generate daily conversation reports
CREATE OR REPLACE FUNCTION public.generate_daily_conversation_reports()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  lead_record RECORD;
  message_count int;
  sentiment_data jsonb;
BEGIN
  -- Loop through leads with activity in the last 24 hours
  FOR lead_record IN
    SELECT DISTINCT l.id, l.parent_name, l.student_name
    FROM public.leads l
    INNER JOIN public.messages m ON l.id = m.lead_id
    WHERE m.timestamp > now() - interval '24 hours'
  LOOP
    -- Count messages for this lead
    SELECT COUNT(*) INTO message_count
    FROM public.messages
    WHERE lead_id = lead_record.id
      AND timestamp > now() - interval '24 hours';

    -- Get sentiment breakdown
    SELECT jsonb_object_agg(
      COALESCE(current_sentiment, 'unknown'),
      1
    ) INTO sentiment_data
    FROM public.leads
    WHERE id = lead_record.id;

    -- Insert or update conversation report
    INSERT INTO public.conversation_reports (
      lead_id,
      report_date,
      message_count,
      sentiment_breakdown,
      emotional_summary,
      academic_summary
    )
    VALUES (
      lead_record.id,
      CURRENT_DATE,
      message_count,
      sentiment_data,
      'Generated by daily cron job - awaiting AI analysis',
      'Pending analysis'
    )
    ON CONFLICT (lead_id, report_date)
    DO UPDATE SET
      message_count = EXCLUDED.message_count,
      sentiment_breakdown = EXCLUDED.sentiment_breakdown,
      created_at = now();
  END LOOP;

  RAISE NOTICE 'Daily conversation reports generated';
END;
$$;

COMMENT ON FUNCTION public.generate_daily_conversation_reports IS 'Generates daily conversation reports for active leads';

-- Create function to identify and notify about inactive leads
CREATE OR REPLACE FUNCTION public.identify_inactive_leads()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  inactive_lead RECORD;
  notification_id uuid;
BEGIN
  -- Find leads inactive for more than 7 days
  FOR inactive_lead IN
    SELECT
      l.id,
      l.parent_name,
      l.student_name,
      l.phone,
      l.status,
      l.last_contact_at
    FROM public.leads l
    WHERE
      l.last_contact_at < now() - interval '7 days'
      AND l.status NOT IN ('COLD', 'ADMITTED')
      AND NOT EXISTS (
        SELECT 1 FROM public.reengagement_logs rl
        WHERE rl.lead_id = l.id
          AND rl.sent_at > now() - interval '7 days'
      )
    LIMIT 50 -- Process max 50 leads per run
  LOOP
    -- Create admin notification
    INSERT INTO public.admin_notifications (
      lead_id,
      type,
      message,
      metadata
    )
    VALUES (
      inactive_lead.id,
      'urgent',
      format('Lead %s (%s) has been inactive for %s days',
        COALESCE(inactive_lead.parent_name, 'Unknown'),
        inactive_lead.phone,
        EXTRACT(day FROM now() - inactive_lead.last_contact_at)
      ),
      jsonb_build_object(
        'reason', 'inactive_lead',
        'days_inactive', EXTRACT(day FROM now() - inactive_lead.last_contact_at),
        'last_contact', inactive_lead.last_contact_at
      )
    )
    RETURNING id INTO notification_id;

  END LOOP;

  RAISE NOTICE 'Inactive lead notifications created';
END;
$$;

COMMENT ON FUNCTION public.identify_inactive_leads IS 'Identifies inactive leads and creates notifications for re-engagement';

-- Create function to update lead scores based on activity
CREATE OR REPLACE FUNCTION public.update_lead_scores()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
BEGIN
  -- Update lead scores based on various factors
  UPDATE public.leads l
  SET score = (
    -- Base score from message frequency (0-30 points)
    LEAST(30, (
      SELECT COUNT(*) * 2
      FROM public.messages m
      WHERE m.lead_id = l.id
        AND m.timestamp > now() - interval '7 days'
    )) +
    -- Sentiment score (0-20 points)
    CASE l.current_sentiment
      WHEN 'happy' THEN 20
      WHEN 'proud' THEN 18
      WHEN 'neutral' THEN 10
      WHEN 'worried' THEN 5
      WHEN 'anxious' THEN 3
      WHEN 'stressed' THEN 3
      WHEN 'angry' THEN 0
      ELSE 10
    END +
    -- Status score (0-20 points)
    CASE l.status
      WHEN 'HOT' THEN 20
      WHEN 'FOLLOW-UP' THEN 15
      WHEN 'WARM' THEN 10
      WHEN 'COLD' THEN 5
      WHEN 'ADMITTED' THEN 0
      ELSE 0
    END +
    -- Payment history score (0-30 points)
    LEAST(30, (
      SELECT COUNT(*) * 10
      FROM public.payments p
      WHERE p.lead_id = l.id
        AND p.status = 'paid'
    ))
  )
  WHERE l.status != 'ADMITTED';

  RAISE NOTICE 'Lead scores updated';
END;
$$;

COMMENT ON FUNCTION public.update_lead_scores IS 'Updates lead scores based on activity, sentiment, and engagement';

-- Create function to archive old conversation insights
CREATE OR REPLACE FUNCTION public.archive_old_insights()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  archived_count int;
BEGIN
  -- Delete insights older than 6 months for admitted/cold leads
  DELETE FROM public.conversation_insights ci
  WHERE ci.extracted_at < now() - interval '6 months'
    AND EXISTS (
      SELECT 1 FROM public.leads l
      WHERE l.id = ci.lead_id
        AND l.status IN ('ADMITTED', 'COLD')
    );
  GET DIAGNOSTICS archived_count = ROW_COUNT;

  RAISE NOTICE 'Archived % old insights', archived_count;
END;
$$;

COMMENT ON FUNCTION public.archive_old_insights IS 'Archives old conversation insights for completed leads';

-- Schedule jobs using pg_cron
-- Note: These will be scheduled when the migration runs

-- Job 1: Daily cleanup at 2 AM
SELECT cron.schedule(
  'daily-cleanup',
  '0 2 * * *', -- Every day at 2 AM
  $$SELECT public.scheduled_cleanup_old_data();$$
);

-- Job 2: Daily conversation reports at 11 PM
SELECT cron.schedule(
  'daily-reports',
  '0 23 * * *', -- Every day at 11 PM
  $$SELECT public.generate_daily_conversation_reports();$$
);

-- Job 3: Identify inactive leads - Runs twice daily (9 AM and 5 PM)
SELECT cron.schedule(
  'identify-inactive-leads',
  '0 9,17 * * *', -- 9 AM and 5 PM daily
  $$SELECT public.identify_inactive_leads();$$
);

-- Job 4: Update lead scores - Runs every 6 hours
SELECT cron.schedule(
  'update-lead-scores',
  '0 */6 * * *', -- Every 6 hours
  $$SELECT public.update_lead_scores();$$
);

-- Job 5: Archive old insights - Weekly on Sunday at 3 AM
SELECT cron.schedule(
  'archive-insights',
  '0 3 * * 0', -- Every Sunday at 3 AM
  $$SELECT public.archive_old_insights();$$
);

-- Create a view to monitor cron jobs
CREATE OR REPLACE VIEW public.cron_job_status AS
SELECT
  jobid,
  schedule,
  command,
  nodename,
  nodeport,
  database,
  username,
  active,
  jobname
FROM cron.job
WHERE database = current_database()
ORDER BY jobname;

COMMENT ON VIEW public.cron_job_status IS 'Monitor status of all scheduled cron jobs';

-- Create function to get cron job history
CREATE OR REPLACE FUNCTION public.get_cron_job_history(
  job_name_filter text DEFAULT NULL,
  limit_rows int DEFAULT 50
)
RETURNS TABLE (
  jobid bigint,
  runid bigint,
  job_name text,
  status text,
  return_message text,
  start_time timestamp with time zone,
  end_time timestamp with time zone,
  duration interval
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    jh.jobid,
    jh.runid,
    j.jobname,
    jh.status,
    jh.return_message,
    jh.start_time,
    jh.end_time,
    (jh.end_time - jh.start_time) as duration
  FROM cron.job_run_details jh
  JOIN cron.job j ON jh.jobid = j.jobid
  WHERE
    (job_name_filter IS NULL OR j.jobname = job_name_filter)
    AND j.database = current_database()
  ORDER BY jh.start_time DESC
  LIMIT limit_rows;
END;
$$;

COMMENT ON FUNCTION public.get_cron_job_history IS 'Get execution history of cron jobs';

-- Create a table to log custom job executions
CREATE TABLE public.cron_execution_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  job_name text NOT NULL,
  executed_at timestamp with time zone DEFAULT now(),
  status text NOT NULL CHECK (status = ANY (ARRAY['success'::text, 'failed'::text, 'partial'::text])),
  details jsonb DEFAULT '{}'::jsonb,
  error_message text,
  duration_ms bigint,
  CONSTRAINT cron_execution_log_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_cron_execution_log_job_name ON public.cron_execution_log(job_name);
CREATE INDEX idx_cron_execution_log_executed_at ON public.cron_execution_log(executed_at);

-- Enable RLS
ALTER TABLE public.cron_execution_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY cron_log_all ON public.cron_execution_log
FOR ALL
TO public
USING (true)
WITH CHECK (true);

COMMENT ON TABLE public.cron_execution_log IS 'Custom log table for tracking cron job executions and their results';

-- Cleanup old cron logs (keep only 30 days)
SELECT cron.schedule(
  'cleanup-cron-logs',
  '0 1 * * *', -- Every day at 1 AM
  $$DELETE FROM public.cron_execution_log WHERE executed_at < now() - interval '30 days';$$
);
